# Generated by Django 5.2.8 on 2025-11-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('target_date', models.DateField(verbose_name='목표 날짜')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '디데이',
                'verbose_name_plural': '디데이',
                'ordering': ['order', 'id'],
            },
        ),
    ]
