# Generated by Django 5.2.8 on 2025-11-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dday',
            name='period',
            field=models.CharField(choices=[('annual', '연간'), ('monthly', '월간'), ('quarterly', '분기')], default='annual', max_length=20, verbose_name='주기'),
        ),
        migrations.AddField(
            model_name='dday',
            name='service_type',
            field=models.CharField(choices=[('visitCare', '방문요양'), ('visitBath', '방문목욕'), ('visitNurse', '방문간호'), ('dayCare', '주야간보호'), ('shortTerm', '단기보호'), ('welfare', '복지용구')], default='visitCare', help_text='이 디데이가 표시될 센터 유형을 선택하세요', max_length=20, verbose_name='센터 유형'),
        ),
    ]
