# Generated by Django 5.2.8 on 2025-11-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_dday_period_dday_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dday',
            name='target_year',
            field=models.IntegerField(blank=True, help_text='연간 주기인 경우 해당 연도를 설정하세요 (예: 2025)', null=True, verbose_name='대상 연도'),
        ),
        migrations.AlterField(
            model_name='dday',
            name='target_date',
            field=models.DateField(blank=True, help_text='주기가 연간이 아닌 경우에만 사용됩니다', null=True, verbose_name='목표 날짜'),
        ),
    ]
