# Generated by Django 5.2.8 on 2025-11-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_dday_target_year_alter_dday_target_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTypeClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('visitCare', '방문요양'), ('visitBath', '방문목욕'), ('visitNurse', '방문간호'), ('dayCare', '주야간보호'), ('shortTerm', '단기보호'), ('welfare', '복지용구')], max_length=20, unique=True, verbose_name='급여 유형')),
                ('click_count', models.IntegerField(default=0, verbose_name='클릭 횟수')),
                ('last_clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 클릭 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '급여 유형 클릭 통계',
                'verbose_name_plural': '급여 유형 클릭 통계',
                'ordering': ['-click_count', 'service_type'],
            },
        ),
    ]
