# Generated by Django 5.2.8 on 2025-11-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_servicetypeclick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dday',
            name='period',
            field=models.CharField(choices=[('annual', '연간'), ('monthly', '월간'), ('quarterly', '분기'), ('semiannual', '반기')], default='annual', max_length=20, verbose_name='주기'),
        ),
    ]
