# Generated by Django 5.2.8 on 2025-11-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0006_alter_dday_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.CharField(help_text='예: dday_1, service_visitBath', max_length=100, unique=True, verbose_name='기능 ID')),
                ('feature_name', models.CharField(max_length=100, verbose_name='기능 이름')),
                ('vote_count', models.IntegerField(default=0, verbose_name='투표 수')),
                ('last_voted_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 투표 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '기능 투표 통계',
                'verbose_name_plural': '기능 투표 통계',
                'ordering': ['-vote_count', 'feature_name'],
            },
        ),
        migrations.AlterField(
            model_name='dday',
            name='target_date',
            field=models.DateField(blank=True, help_text='주간 주기: 해당 날짜의 요일을 기준으로 매주 그 요일이 목표 날짜가 됩니다 (예: 2025-11-16을 입력하면 매주 일요일). 월간/분기/반기 주기: 사용되지 않습니다.', null=True, verbose_name='목표 날짜'),
        ),
    ]
