# Generated by Django 5.2.8 on 2025-11-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0007_featurevote_alter_dday_target_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurevote',
            name='status',
            field=models.CharField(choices=[('pending', '개발 대기'), ('in_progress', '개발 중'), ('completed', '개발 완료')], default='pending', max_length=20, verbose_name='개발 상태'),
        ),
    ]
