# Generated by Django 5.2.8 on 2025-11-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0008_featurevote_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserServicePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('visitCare', '방문요양'), ('visitBath', '방문목욕'), ('visitNurse', '방문간호'), ('dayCare', '주야간보호'), ('shortTerm', '단기보호'), ('welfare', '복지용구')], max_length=20, unique=True, verbose_name='급여 유형')),
                ('selection_count', models.IntegerField(default=0, verbose_name='선택 횟수')),
                ('last_selected_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 선택 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '급여 유형 선택 통계',
                'verbose_name_plural': '급여 유형 선택 통계',
                'ordering': ['-selection_count', 'service_type'],
            },
        ),
    ]
