# Generated by Django 5.2.8 on 2025-11-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0009_userservicepreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dday',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='활성화'),
        ),
        migrations.AlterField(
            model_name='dday',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='제목'),
        ),
        migrations.AddIndex(
            model_name='dday',
            index=models.Index(fields=['is_active', 'title'], name='theme_dday_is_acti_d15c9a_idx'),
        ),
    ]
