# Generated by Django 5.2.8 on 2025-11-12 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0010_alter_dday_is_active_alter_dday_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.CharField(help_text='고유한 기능 ID (예: ai_chatbot, dday_1, service_visitBath)', max_length=100, unique=True, verbose_name='기능 ID')),
                ('feature_name', models.CharField(max_length=100, verbose_name='기능 이름')),
                ('description', models.TextField(help_text='기능에 대한 상세 설명', verbose_name='설명')),
                ('feature_type', models.CharField(choices=[('ai_writing', 'AI 작성하기'), ('service_type', '급여 유형'), ('other', '기타')], default='other', max_length=20, verbose_name='기능 유형')),
                ('service_type', models.CharField(blank=True, choices=[('visitCare', '방문요양'), ('visitBath', '방문목욕'), ('visitNurse', '방문간호'), ('dayCare', '주야간보호'), ('shortTerm', '단기보호'), ('welfare', '복지용구')], help_text='급여 유형 관련 기능인 경우 선택하세요', max_length=20, null=True, verbose_name='관련 급여 유형')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='활성화')),
                ('order', models.IntegerField(default=0, help_text='표시 순서 (낮을수록 먼저 표시)', verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('related_dday', models.ForeignKey(blank=True, help_text='디데이 관련 기능인 경우 선택하세요', null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.dday', verbose_name='관련 디데이')),
            ],
            options={
                'verbose_name': '기능 개발 요청',
                'verbose_name_plural': '기능 개발 요청',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='theme_featu_is_acti_fbc4e7_idx')],
            },
        ),
    ]
